(function(c){var b=window.AmazonUIPageJS||window.P,f=b._namespace||b.attributeErrors,a=f?f("DetailPageNostosAssets",""):b;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,b,f){c.when("A").register("nostos-metrics",function(a){return{addCSMTag:function(a){b.ue&&b.ue.tag&&b.ue.tag(a)},addCount:function(a){b.ue&&b.ue.count&&b.ue.count(a,(b.ue.count(a)||0)+1)}}});c.declare("nostos-buybox-config",{selectors:{buyboxTabSet:"#offerDisplayGroupTabSet",buyboxAccordionRows:"#buyBoxAccordion",
nostosBadges:"buyingOptionNostosBadge_feature_div"},tabs:{tab_desktop_buybox_group_1:"#tab_heading_desktop_buybox_group_1",tab_desktop_buybox_group_2:"#tab_heading_desktop_buybox_group_2",tab_mobile_buybox_group_1:"#tab_heading_mobile_buybox_group_1",tab_mobile_buybox_group_2:"#tab_heading_mobile_buybox_group_2",tab_mobileapp_buybox_group_1:"#tab_heading_mobileapp_buybox_group_1",tab_mobileapp_buybox_group_2:"#tab_heading_mobileapp_buybox_group_2"},accordionRowsToNostos:{newAccordionRow:"NEW_1_nostos_badge",
SecondNewAccordionRow:"NEW_2_nostos_badge",pwBuyBoxAccordionRow:"PRIME_WARDROBE_1_nostos_badge",usedAccordionRow:"USED_1_nostos_badge",snsAccordionRow:"SNS_1_nostos_badge",snsAccordionRowMovedUp:"SNS_1_nostos_badge",snsAccordionRowMiddle:"SNS_1_nostos_badge",snsAccordionRowMobileMiddle:"SNS_1_nostos_badge",snsAccordionRowMobileAppMiddle:"SNS_1_nostos_badge",dealsAccordionRow:"LIGHTNING_DEAL_1_nostos_badge",renewedTier1AccordionRow:"RENEWED_TIER_1_1_nostos_badge",mobile_renewedTier1AccordionRow:"RENEWED_TIER_1_1_nostos_badge",
mobileApp_renewedTier1AccordionRow:"RENEWED_TIER_1_1_nostos_badge",renewedTier2AccordionRow:"RENEWED_TIER_2_1_nostos_badge",mobile_renewedTier2AccordionRow:"RENEWED_TIER_2_1_nostos_badge",mobileApp_renewedTier2AccordionRow:"RENEWED_TIER_2_1_nostos_badge",renewedTier3AccordionRow:"RENEWED_TIER_3_1_nostos_badge",mobile_renewedTier3AccordionRow:"RENEWED_TIER_3_1_nostos_badge",mobileApp_renewedTier3AccordionRow:"RENEWED_TIER_3_1_nostos_badge",renewedTier4AccordionRow:"RENEWED_TIER_4_1_nostos_badge",mobile_renewedTier4AccordionRow:"RENEWED_TIER_4_1_nostos_badge",
mobileApp_renewedTier4AccordionRow:"RENEWED_TIER_4_1_nostos_badge"},nostosToAccordionRows:{NEW_1_nostos_badge:["newAccordionRow_0","newAccordionRow_1","newAccordionRow_2","newAccordionRow_3"],NEW_2_nostos_badge:["newAccordionRow_1","newAccordionRow_2","newAccordionRow_3","newAccordionRow_4"],PRIME_WARDROBE_1_nostos_badge:["pwBuyBoxAccordionRow"],USED_1_nostos_badge:["usedAccordionRow"],SNS_1_nostos_badge:["snsAccordionRow","snsAccordionRowMovedUp","snsAccordionRowMiddle","snsAccordionRowMobileMiddle",
"snsAccordionRowMobileAppMiddle"],LIGHTNING_DEAL_1_nostos_badge:["dealsAccordionRow"],RENEWED_TIER_1_1_nostos_badge:["renewedTier1AccordionRow","mobile_renewedTier1AccordionRow","mobileApp_renewedTier1AccordionRow"],RENEWED_TIER_2_1_nostos_badge:["renewedTier2AccordionRow","mobile_renewedTier2AccordionRow","mobileApp_renewedTier2AccordionRow"],RENEWED_TIER_3_1_nostos_badge:["renewedTier3AccordionRow","mobile_renewedTier3AccordionRow","mobileApp_renewedTier3AccordionRow"],RENEWED_TIER_4_1_nostos_badge:["renewedTier4AccordionRow",
"mobile_renewedTier4AccordionRow","mobileApp_renewedTier4AccordionRow"]},nostosToSingleOffer:{NEW_1_nostos_badge:["qualifiedBuybox_globalMatchbox_3","qualifiedBuybox_globalMatchbox_2","qualifiedBuybox_globalMatchbox_1","qualifiedBuybox"],USED_1_nostos_badge:["used_buybox_desktop","used_buybox_mobile","used_buybox_mobileApp"],PICKUP_1_nostos_badge:["pickupOfferDisplay_Desktop","pickupOfferDisplay_Mobile","pickupOfferDisplay_MobileApp"],LIGHTNING_DEAL_1_nostos_badge:["deals_singleOfferDisplay_Desktop",
"deals_singleOfferDisplay_Mobile","deals_singleOfferDisplay_MobileApp"]}});"use strict";c.when("A","nostos-metrics","nostos-buybox-config","customer-returns-badge","load").register("nostos-buying-option-controller",function(a,b,k){var d=a.$;b.addCSMTag("buyingOptionNostos");var c,r,m,l,h=function(){c=0<d(k.selectors.buyboxTabSet).length;r=0<d(k.selectors.buyboxAccordionRows).length;for(var g=document.querySelectorAll("#buyingOptionNostosBadge_feature_div \x3e div"),a=[],e=0;e<g.length;e++)a.push(g[e].id);
m=a;if(c)a:{for(var b in k.tabs)if(d(k.tabs[b]).hasClass("a-active")){l=b;break a}l=f}};h();var t=function(g){g=k.nostosToSingleOffer[g];if(g!==f)for(var a=0;a<g.length;a++)if(0<d("#"+g[a]).length){var b=g[a];if(c){if(document.getElementById(l)!==f&&document.getElementById(l).contains(document.getElementById(b)))return!0}else return!0}return!1},n=function(a){d(a).addClass("aok-hidden")},p=function(a){d(a).removeClass("aok-hidden")},q=function(){for(var a=0;a<m.length;a++){var b=m[a];if(r){a:{var e=
k.nostosToAccordionRows[b];if(e!==f)for(var h=0;h<e.length;h++)if(d("#"+e[h]).hasClass("a-accordion-active")){var n=e[h];if(c){if(document.getElementById(l)!==f&&document.getElementById(l).contains(document.getElementById(n))){e=!0;break a}}else{e=!0;break a}}e=!1}if(e||t(b)){p("#"+m[a]);break}}else if(t(b)){p("#"+m[a]);break}}};q();(function(){a.on("a:tabs:offerDisplayGroup_tabs:select",function(a){n(d("[id$\x3d_nostos_badge]"));l=a.selectedTab.tabName;q()})})();(function(){a.on("a:accordion:buybox-accordion:select",
function(a){n(d("[id$\x3d_nostos_badge]"));p("#"+k.accordionRowsToNostos[a.selectedRow.rowName])})})();(function(){a.on("a:pageUpdate",function(){n(d("[id$\x3d_nostos_badge]"));h();q()})})()});"use strict";c.when("A","nostos-metrics","load").register("customer-returns-badge",function(a,b){var c=a.$,d=[".hcr-badge",".lcr-badge",".hrrv-badge"];b.addCSMTag("nostosCustomerReturnsBadge");var f=function(){(0<c("#softlines_substitute_return_reason_container").length||0<c("#softlines_return_reason_message").length)&&
d.forEach(function(a){0<c(a).length&&(c(a).addClass("aok-hidden"),b.addCount("nostosReturnsBadgeSuppressed"))})};f();(function(){a.on("a:pageUpdate",function(){f()})})()})});